# Generated by Django 5.2.7 on 2025-10-31 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesTypeL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTagsTypeL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
                ('Body', models.TextField()),
                ('Thumbnail', models.ImageField(blank=True, null=True, upload_to='ArticleImg/')),
                ('ArticleTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.articlestypel')),
                ('ArticleTagsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.articletagstypel')),
            ],
        ),
    ]
