# Generated by Django 5.2.7 on 2025-11-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='ArticleTagsID',
        ),
        migrations.RemoveField(
            model_name='article',
            name='ArticleTypeID',
        ),
        migrations.DeleteModel(
            name='ArticleTagsTypeL',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticlesTypeL',
        ),
    ]
